<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>روتانا | إدارة الأسطول والمشتريات</title>
@foreach(['bootstrap.rtl.min.css','select2.min.css','dataTables.dataTables.min.css','toastr.min.css','css/all.min.css'] as $css)<link rel="stylesheet" href="/assets/vendor/{{ $css }}">@endforeach
<link rel="stylesheet" href="/assets/dashboard-refresh.css?v={{ hash_file('sha256', public_path('assets/dashboard-refresh.css')) }}"><link rel="stylesheet" href="/assets/dashboard-overview.css?v={{ hash_file('sha256', public_path('assets/dashboard-overview.css')) }}"><link rel="stylesheet" href="/assets/dashboard-stage.css?v={{ hash_file('sha256', public_path('assets/dashboard-stage.css')) }}"><link rel="stylesheet" href="/assets/vehicle-log.css?v={{ hash_file('sha256', public_path('assets/vehicle-log.css')) }}">
<link rel="stylesheet" href="/assets/dashboard-reference.css?v={{ hash_file('sha256', public_path('assets/dashboard-reference.css')) }}">
<link rel="stylesheet" href="/assets/dashboard-metrics.css?v={{ hash_file('sha256', public_path('assets/dashboard-metrics.css')) }}"><link rel="stylesheet" href="/assets/dashboard-layout.css?v={{ hash_file('sha256', public_path('assets/dashboard-layout.css')) }}">
<link rel="stylesheet" href="/assets/app.css?v={{ hash_file('sha256', public_path('assets/app.css')) }}"><link rel="stylesheet" href="/assets/workflow.css?v={{ hash_file('sha256', public_path('assets/workflow.css')) }}"><link rel="stylesheet" href="/assets/table-ui.css?v={{ hash_file('sha256', public_path('assets/table-ui.css')) }}"><style>.modal-body{max-height:76vh;overflow:auto}.table{width:100%!important}.table td{vertical-align:middle}.select2-container{max-width:100%}.select2-selection{min-height:43px!important}.action-bar{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.photo-preview{width:100%;height:105px;object-fit:cover}.document-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.field{min-width:0}.badge{font-weight:500}.workflow-steps{display:flex;gap:8px;flex-wrap:wrap}.workflow-steps span{padding:7px 12px;border-radius:999px;background:#eef3f9;font-size:13px}.workflow-steps .current{background:#0866ff;color:#fff}@media(max-width:800px){#sidebar{transform:translateX(100%)}#sidebar.open{transform:translateX(0)}.workspace{margin-right:0}main{padding:18px 12px}.form-grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.topbar{padding:0 15px}}</style><script>window.rotanaUi=@json(\App\Support\UiText::frontend(), JSON_UNESCAPED_UNICODE);</script></head><body class="app-shell">
<aside id="sidebar"><a class="brand" href="#dashboard"><i class="fa-solid fa-car-side"></i><div>روتانا<small>إدارة الأسطول والمشتريات</small></div></a><nav id="navigation"></nav><div class="sidebar-foot">منصة تشغيل موحدة<small>المشتريات، الصيانة، المخزون، والمتابعة المالية</small></div></aside><div class="workspace"><header class="topbar"><button id="menu-toggle" class="btn btn-light topbar-icon" type="button" aria-label="فتح القائمة"><i class="fa-solid fa-bars"></i></button><div class="topbar-title"><strong>روتانا</strong><small>إدارة الأسطول والمشتريات</small></div><div class="global-search" role="search"><label class="visually-hidden" for="global-search-input">البحث العام</label><i class="fa-solid fa-magnifying-glass"></i><input id="global-search-input" type="search" autocomplete="off" placeholder="بحث سريع" aria-autocomplete="list" aria-expanded="false" aria-controls="global-search-results"><button id="global-search-clear" type="button" aria-label="مسح البحث" hidden><i class="fa-solid fa-xmark"></i></button><div id="global-search-results" class="global-search-results" role="listbox" hidden></div></div><div class="d-flex align-items-center gap-3"><span class="user-name"><bdi>{{ auth()->user()->name }}</bdi></span><form action="/logout" method="post">@csrf<button class="btn btn-light topbar-icon" type="submit" title="تسجيل الخروج" aria-label="تسجيل الخروج"><i class="fa-solid fa-right-from-bracket"></i></button></form></div></header><main id="content"><div class="panel">جاري تحميل البيانات...</div></main><footer>روتانا<span>جميع القيم المعروضة بالريال السعودي</span></footer></div>
<div class="modal fade" id="editor" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5"></h2><button class="btn-close" data-bs-dismiss="modal" aria-label="إغلاق"></button></div><form id="editor-form"><div class="modal-body"></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">إلغاء</button><button class="btn btn-primary" type="submit">حفظ البيانات</button></div></form></div></div></div>
@foreach(['jquery.min.js','bootstrap.bundle.min.js','select2.min.js','dataTables.min.js','sweetalert2.all.min.js','toastr.min.js','apexcharts.min.js'] as $js)<script src="/assets/vendor/{{ $js }}"></script>@endforeach
<link rel="stylesheet" href="/assets/search-detail-refresh.css?v={{ hash_file('sha256', public_path('assets/search-detail-refresh.css')) }}"><link rel="stylesheet" href="/assets/search-overlay.css?v={{ hash_file('sha256', public_path('assets/search-overlay.css')) }}"><script src="/assets/server.js?v={{ hash_file('sha256', public_path('assets/server.js')) }}"></script></body></html>
