<?php

return [
    'categories' => ['maintenance' => 'صيانة سيارات', 'damage' => 'حوادث وتلفيات', 'parts' => 'قطع غيار سيارات', 'utilities' => 'كهرباء ومياه وخدمات', 'branches' => 'مصروفات الفروع', 'stock' => 'تزويد مخزون', 'quotes' => 'عروض الأسعار'],
    'statuses' => ['draft' => 'مسودة', 'accountant' => 'مراجعة المحاسب', 'manager' => 'اعتماد المدير', 'supervisor' => 'اعتماد المشرف', 'matching' => 'مطابقة قبل التحويل', 'ready' => 'جاهز للتحويل', 'paid' => 'تم التحويل', 'closed' => 'مغلق', 'rejected' => 'مرفوض'],
    'photo_labels' => ['front' => 'أمام', 'back' => 'خلف', 'right' => 'يمين', 'left' => 'يسار', 'angle_front' => 'أمامي يمين', 'angle_back' => 'خلفي يسار', 'interior' => 'الداخلية', 'odometer' => 'العداد', 'damage' => 'موضع الضرر'],
    'permissions' => ['dashboard.view', 'orders.view', 'orders.create', 'orders.update', 'orders.submit', 'orders.review', 'orders.approve_manager', 'orders.approve_supervisor', 'orders.approve_own', 'orders.reject', 'orders.match', 'orders.close', 'orders.delete', 'receipts.manage', 'invoices.manage', 'payments.create', 'media.upload', 'inventory.view', 'inventory.issue', 'inventory.transfer', 'inventory.return', 'inventory.adjust', 'inventory.delete', 'cards.view', 'cards.manage', 'vehicles.view', 'vehicles.manage', 'suppliers.view', 'suppliers.manage', 'items.view', 'items.manage', 'masters.manage', 'masters.delete', 'users.manage', 'roles.manage', 'activity.view', 'reports.view', 'excel.import', 'excel.export'],
    'role_labels' => [
        'admin' => 'مدير النظام',
        'employee' => 'موظف الفرع',
        'accountant' => 'المحاسب',
        'manager' => 'مدير الإدارة',
        'supervisor' => 'المشرف',
        'treasurer' => 'أمين الخزينة',
        'warehouse' => 'أمين المستودع',
        'maintenance' => 'مسؤول الصيانة',
        'auditor' => 'المراجع',
    ],
    'permission_groups' => [
        ['key' => 'dashboard', 'label' => 'لوحة التحكم', 'permissions' => ['dashboard.view']],
        ['key' => 'orders', 'label' => 'طلبات الشراء', 'permissions' => ['orders.view', 'orders.create', 'orders.update', 'orders.submit', 'orders.delete']],
        ['key' => 'approvals', 'label' => 'الاعتمادات', 'permissions' => ['orders.review', 'orders.approve_manager', 'orders.approve_supervisor', 'orders.approve_own', 'orders.reject', 'orders.match', 'orders.close']],
        ['key' => 'receipts', 'label' => 'الاستلام', 'permissions' => ['receipts.manage']],
        ['key' => 'invoices', 'label' => 'الفواتير', 'permissions' => ['invoices.manage']],
        ['key' => 'payments', 'label' => 'المدفوعات', 'permissions' => ['payments.create']],
        ['key' => 'attachments', 'label' => 'المرفقات', 'permissions' => ['media.upload']],
        ['key' => 'inventory', 'label' => 'المخزون', 'permissions' => ['inventory.view', 'inventory.issue', 'inventory.transfer', 'inventory.return', 'inventory.adjust', 'inventory.delete']],
        ['key' => 'maintenance', 'label' => 'الصيانة', 'permissions' => ['cards.view', 'cards.manage']],
        ['key' => 'vehicles', 'label' => 'السيارات', 'permissions' => ['vehicles.view', 'vehicles.manage']],
        ['key' => 'suppliers', 'label' => 'الموردون', 'permissions' => ['suppliers.view', 'suppliers.manage']],
        ['key' => 'items', 'label' => 'الأصناف', 'permissions' => ['items.view', 'items.manage']],
        ['key' => 'masters', 'label' => 'البيانات الأساسية', 'permissions' => ['masters.manage', 'masters.delete']],
        ['key' => 'users', 'label' => 'المستخدمون', 'permissions' => ['users.manage']],
        ['key' => 'roles', 'label' => 'الأدوار والصلاحيات', 'permissions' => ['roles.manage']],
        ['key' => 'reports', 'label' => 'التقارير', 'permissions' => ['reports.view']],
        ['key' => 'excel', 'label' => 'الاستيراد والتصدير', 'permissions' => ['excel.import', 'excel.export']],
        ['key' => 'activity', 'label' => 'سجل النشاطات', 'permissions' => ['activity.view']],
    ],
    'permission_catalog' => [
        'dashboard.view' => ['group' => 'dashboard', 'label' => 'عرض لوحة التحكم', 'description' => 'يسمح بالوصول إلى مؤشرات النظام والملخصات التشغيلية.'],
        'orders.view' => ['group' => 'orders', 'label' => 'عرض طلبات الشراء', 'description' => 'يسمح بمشاهدة الطلبات وسجل مراحلها وبياناتها.'],
        'orders.create' => ['group' => 'orders', 'label' => 'إنشاء طلب شراء', 'description' => 'يسمح بتسجيل طلب جديد وحفظه كمسودة.'],
        'orders.update' => ['group' => 'orders', 'label' => 'تعديل مسودات الطلبات', 'description' => 'يسمح بتعديل الطلبات قبل الاستلام واعتمادها النهائي.'],
        'orders.submit' => ['group' => 'orders', 'label' => 'إرسال الطلب للمراجعة', 'description' => 'يسمح بإرسال المسودة إلى مسار الاعتمادات.'],
        'orders.review' => ['group' => 'approvals', 'label' => 'الاعتماد المحاسبي', 'description' => 'يسمح بمراجعة الطلب واعتماده في المرحلة المحاسبية.'],
        'orders.approve_manager' => ['group' => 'approvals', 'label' => 'اعتماد المدير', 'description' => 'يسمح باعتماد الطلب في مرحلة الإدارة.'],
        'orders.approve_supervisor' => ['group' => 'approvals', 'label' => 'اعتماد المشرف', 'description' => 'يسمح باعتماد الطلب في مرحلة الإشراف.'],
        'orders.approve_own' => ['group' => 'approvals', 'label' => 'اعتماد الطلب الشخصي', 'description' => 'يسمح باعتماد الطلب الذي أنشأه المستخدم بنفسه عند الحاجة.'],
        'orders.reject' => ['group' => 'approvals', 'label' => 'إعادة أو رفض الطلب', 'description' => 'يسمح بإرجاع الطلب للتعديل أو رفضه مع تسجيل السبب.'],
        'orders.match' => ['group' => 'approvals', 'label' => 'اعتماد المطابقة', 'description' => 'يسمح باعتماد تطابق الاستلام والفاتورة والقيمة.'],
        'orders.close' => ['group' => 'approvals', 'label' => 'إغلاق الطلب', 'description' => 'يسمح بإغلاق الطلب بعد سداد قيمته واكتمال الدورة.'],
        'orders.delete' => ['group' => 'orders', 'label' => 'حذف مسودات الطلبات', 'description' => 'يسمح بحذف طلبات الشراء التي لم تدخل الدورة المالية أو التشغيلية.'],
        'receipts.manage' => ['group' => 'receipts', 'label' => 'إدارة الاستلام', 'description' => 'يسمح بتسجيل الاستلام الفعلي وتصحيحه للكميات المستلمة.'],
        'invoices.manage' => ['group' => 'invoices', 'label' => 'إدارة الفواتير', 'description' => 'يسمح بإدخال فاتورة المورد وربطها بمرفقاتها.'],
        'payments.create' => ['group' => 'payments', 'label' => 'تسجيل المدفوعات', 'description' => 'يسمح بتسجيل الحوالات المالية وإثباتاتها.'],
        'media.upload' => ['group' => 'attachments', 'label' => 'رفع المرفقات', 'description' => 'يسمح برفع الصور والملفات والوثائق المرتبطة بالطلبات.'],
        'inventory.view' => ['group' => 'inventory', 'label' => 'عرض المخزون', 'description' => 'يسمح بمشاهدة الأرصدة والحركات المخزنية.'],
        'inventory.issue' => ['group' => 'inventory', 'label' => 'صرف مخزني', 'description' => 'يسمح بصرف أصناف من المخزن إلى سيارة أو عملية تشغيلية.'],
        'inventory.transfer' => ['group' => 'inventory', 'label' => 'تحويل بين المخازن', 'description' => 'يسمح بتحويل الأصناف بين مخازن الفروع.'],
        'inventory.return' => ['group' => 'inventory', 'label' => 'مرتجع مخزني', 'description' => 'يسمح بإرجاع الأصناف المصروفة إلى المخزن.'],
        'inventory.adjust' => ['group' => 'inventory', 'label' => 'تسوية جرد', 'description' => 'يسمح بتعديل الرصيد الفعلي بناءً على الجرد.'],
        'inventory.delete' => ['group' => 'inventory', 'label' => 'حذف قيود المخزون الآمنة', 'description' => 'يسمح بحذف حركة يمكن عكس أثرها بأمان أو رصيد صفري فقط.'],
        'cards.view' => ['group' => 'maintenance', 'label' => 'عرض كروت الصيانة', 'description' => 'يسمح بمشاهدة كروت الصيانة ومراحلها والطلبات المرتبطة بها.'],
        'cards.manage' => ['group' => 'maintenance', 'label' => 'إدارة كروت الصيانة', 'description' => 'يسمح بإنشاء كروت الصيانة وتحديث مراحلها.'],
        'vehicles.view' => ['group' => 'vehicles', 'label' => 'عرض السيارات', 'description' => 'يسمح بعرض بيانات السيارات وحالتها التشغيلية.'],
        'vehicles.manage' => ['group' => 'vehicles', 'label' => 'إدارة السيارات', 'description' => 'يسمح بإضافة السيارات وتحديث بياناتها.'],
        'suppliers.view' => ['group' => 'suppliers', 'label' => 'عرض الموردين', 'description' => 'يسمح بعرض الموردين وبيانات التواصل الخاصة بهم.'],
        'suppliers.manage' => ['group' => 'suppliers', 'label' => 'إدارة الموردين', 'description' => 'يسمح بإضافة الموردين وتحديث بياناتهم.'],
        'items.view' => ['group' => 'items', 'label' => 'عرض الأصناف', 'description' => 'يسمح بعرض الأصناف وتكاليفها وحدود الطلب.'],
        'items.manage' => ['group' => 'items', 'label' => 'إدارة الأصناف', 'description' => 'يسمح بإضافة الأصناف وتحديث خصائص المخزون لها.'],
        'masters.manage' => ['group' => 'masters', 'label' => 'إدارة البيانات الأساسية', 'description' => 'يسمح بإدارة المناطق والفروع والمخازن ومراكز التكلفة والبيانات المرجعية.'],
        'masters.delete' => ['group' => 'masters', 'label' => 'حذف البيانات الأساسية', 'description' => 'يسمح بحذف السجلات المرجعية غير المرتبطة بعمليات أو حسابات.'],
        'users.manage' => ['group' => 'users', 'label' => 'إدارة المستخدمين', 'description' => 'يسمح بإنشاء المستخدمين وتحديث أدوارهم وفروعهم.'],
        'roles.manage' => ['group' => 'roles', 'label' => 'إدارة الأدوار والصلاحيات', 'description' => 'يسمح بإنشاء الأدوار وتعديل الصلاحيات المعروضة لكل دور.'],
        'activity.view' => ['group' => 'activity', 'label' => 'عرض سجل النشاطات', 'description' => 'يسمح بمشاهدة سجل الحركات والتغييرات في النظام.'],
        'reports.view' => ['group' => 'reports', 'label' => 'عرض التقارير', 'description' => 'يسمح بالوصول إلى تقارير الطلبات ومخرجات المتابعة.'],
        'excel.import' => ['group' => 'excel', 'label' => 'استيراد إكسل', 'description' => 'يسمح برفع ملفات الجداول لاستيراد البيانات دفعة واحدة.'],
        'excel.export' => ['group' => 'excel', 'label' => 'تصدير إكسل', 'description' => 'يسمح بتنزيل البيانات الحالية في ملفات جداول.'],
    ],
    'demo_password' => env('DEMO_PASSWORD'),
];
